services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama

  web-ui:
    build: ./web-ui
    ports:
      - "8085:80"
    depends_on:
      - ollama
    container_name: ollama-webui

volumes:
  ollama_data:
